title: Robert Da Silva
author: Robert Da Silva
email: webmaster@robdasilva.com
description: Full-stack developer with a background in Media Design

google_analytics: UA-161447979-1
linkedin: robdasilva
medium: robdasilva
stackoverflow:
  id: 12118217
  username: robdasilva

collections:
  - sections

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

timezone: UTC
