title: Robert Schweizer
author: Robert Schweizer
email: mail@robertschweizer.me
description: Full-stack developer with a background in Media Design

linkedin: rschweizer

collections:
  - sections

plugins:
  - jekyll-seo-tag

sass:
  style: compressed

timezone: UTC
